name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - run: npm run build

      - name: List directories
        run: ls -l

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3

        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

